[package]
name = "lambda"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
backend_logic = { path = "../backend_logic" }
lambda_http = "0.13.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
tokio = { version = "1", features = ["macros"] }
