name: Build Lambda

on:
  push

jobs:
  build-lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache cargo-lambda
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/cargo-lambda
          key: expect-no-change

      - name: Install cargo-lambda if not exists
        run: |
          if ! cargo lambda --version
          then
          cargo install cargo-lambda
          fi

      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build Lambda
        run: |
          npm install -g @ziglang/cli
          cargo lambda build --release

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Deploy Lambda to AWS
        run: |
          cargo lambda deploy --binary-name rust_aws_lambda lambda --enable-function-url
