name: Migrate to Latest Version of DB

on:
  push:
  workflow_dispatch:

jobs:
  migrate-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache utility executables
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/cargo-lambda
            ~/.cargo/bin/sqlx
          key: util_exec_cargo-lamba_sqlx
          restore-keys: |
            util_exec

      - name: Install utility executables if necessary
        run: |
          if ! cargo lambda --version
          then
          cargo install cargo-lambda
          fi
          if ! sqlx --version
          then
          cargo install sqlx-cli
          fi
      
      - name: Migrate DB to Latest Version
        run: |
          sqlx migrate run --no-dotenv --source migrations --database-url ${{ secrets.DATABASE_URL }}
