name: Migrate to Current Configured Version of DB

on:
  push:
    branches:
      - main
      - migration_lambda
  workflow_dispatch:

jobs:
  migrate-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Utility Executables
        uses: ./.github/actions/get-util-execs
      
      - name: prepare and deploy aws lambda for migration
        working-directory: ./migrations
        run: |
          cp $(which sqlx) .
          chmod +x ./bootstrap
          zip lambda.zip bootstrap sqlx migrate.sh current_version.txt sql/*
          aws lambda update-function-code --function-name migrate-database-v1 --zip-file fileb://lambda.zip
