name: Migrate to Current Configured Version of DB

on:
  push:
    branches:
      - main
      - migration_lambda
  workflow_dispatch:

jobs:
  migrate-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache utility executables
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/cargo-lambda
            ~/.cargo/bin/sqlx
          key: util_exec_cargo-lambda_sqlx
          restore-keys: |
            util_exec

      - name: Install utility executables if necessary
        shell: bash
        run: |
          if ! cargo lambda --version
          then
          cargo install cargo-lambda
          fi
          if ! sqlx --version
          then
          cargo install sqlx-cli
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      
      - name: Prepare and Deploy AWS Lambda for Migration
        working-directory: ./migrations
        run: |
          cp $(which sqlx) .
          chmod +x ./bootstrap
          man zip
          zip -X lambda.zip bootstrap sqlx migrate.sh current_version.txt sql/*
          aws lambda update-function-code --function-name ${{ secrets.AWS_MIGRATION_LAMBDA_NAME }} --zip-file fileb://lambda.zip --publish &> /dev/null
      
      - name: Invoke AWS Lambda for Migration
        run: |
          aws lambda invoke --function-name ${{ secrets.AWS_MIGRATION_LAMBDA_NAME }} output.json &> /dev/null
          cat output.json
