name: Migrate to Latest Version of DB

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  migrate-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/workflows/get-util-execs.yml
      
      - name: Migrate DB to Latest Version
        run: |
          sqlx migrate run --no-dotenv --source migrations --database-url ${{ secrets.DATABASE_URL }}
