name: Undo Latest DB Migration

on:
  workflow_dispatch:

jobs:
  migrate-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Utility Executables
        uses: ./.github/actions/get-util-execs
      
      - name: Show Current Migration Version
        run: |
          sqlx migrate info --no-dotenv --source migrations --database-url ${{ secrets.DATABASE_URL }}
      
      - name: Migrate DB to Latest Version
        run: |
          sqlx migrate revert --no-dotenv --source migrations --database-url ${{ secrets.DATABASE_URL }}